# Generated by Django 5.2.5 on 2026-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона для перевода', max_length=20, verbose_name='Телефон привязанный к банку')),
                ('bank_name', models.CharField(blank=True, help_text='Например: Kaspi, Halyk, Jusan', max_length=100, verbose_name='Название банка')),
                ('card_holder_name', models.CharField(blank=True, help_text='Имя как на банковской карте', max_length=255, verbose_name='ФИО владельца карты')),
                ('is_onboarded', models.BooleanField(default=False, verbose_name='Прошёл онбординг')),
                ('has_excluded_reviews', models.BooleanField(blank=True, help_text='Ответ на вопрос об исключении отзывов', null=True, verbose_name='Исключали отзывы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('total_completed', models.PositiveIntegerField(default=0, verbose_name='Выполнено выкупов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
