# Generated by Django 5.2.5 on 2026-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Язык'),
        ),
    ]
