# Generated by Django 5.2.5 on 2026-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='has_excluded_reviews',
            field=models.BooleanField(blank=True, help_text='Ответ на вопрос об исключении отзывов', null=True, verbose_name='Исключали отзывы'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_onboarded',
            field=models.BooleanField(default=False, verbose_name='Прошёл онбординг'),
        ),
    ]
