# Generated by Django 5.2.5 on 2026-02-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_add_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='bonus_bot_user',
            field=models.BooleanField(default=False, verbose_name='Пользователь бонус-бота'),
        ),
    ]
