# Generated by Django 5.2.5 on 2026-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_telegramuser_has_excluded_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='card_number',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Например: Kaspi, Halyk, Jusan', max_length=100, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='card_holder_name',
            field=models.CharField(blank=True, help_text='Имя как на банковской карте', max_length=255, verbose_name='ФИО владельца карты'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона для перевода', max_length=20, verbose_name='Телефон привязанный к банку'),
        ),
    ]
