# Generated by Django 5.2.5 on 2026-02-24 15:40

from django.db import migrations


def backfill(apps, schema_editor):
    """Mark users who have bonus messages as bonus_bot_user."""
    TelegramUser = apps.get_model('account', 'TelegramUser')
    TelegramUser.objects.filter(bonus_messages__isnull=False).distinct().update(
        bonus_bot_user=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_add_bonus_bot_user'),
        ('bonus', '0002_migrate_to_telegramuser'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
