# Generated by Django 5.2.5 on 2026-02-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('catalog', '0002_alter_product_limit_per_user_days_and_more'),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='Текущий шаг')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('on_moderation', 'На модерации'), ('pending_review', 'Ожидает проверки'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён'), ('expired', 'Истёк')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buybacks', to='catalog.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buybacks', to='account.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выкуп',
                'verbose_name_plural': 'Выкупы',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BuybackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(default=dict, help_text='photo, text, value и т.д.', verbose_name='Данные ответа')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('auto_approved', 'Авто-одобрен')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('buyback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pipeline.buyback', verbose_name='Выкуп')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='steps.taskstep', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Ответ на шаг',
                'verbose_name_plural': 'Ответы на шаги',
                'ordering': ['buyback', 'step__order'],
            },
        ),
    ]
