# Generated by Django 5.2.5 on 2026-02-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
        ('steps', '0002_taskstep_publish_time_alter_taskstep_step_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('before_3h', 'За 3 часа'), ('before_2h', 'За 2 часа'), ('before_1h', 'За 1 час'), ('before_5m', 'За 5 минут'), ('overdue', 'Просрочено')], max_length=20, verbose_name='Тип напоминания')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('overdue_count', models.PositiveIntegerField(default=0, help_text='Сколько раз отправлено напоминание о просрочке', verbose_name='Счётчик просрочки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('buyback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pipeline.buyback', verbose_name='Выкуп')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='steps.taskstep', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
