# Generated by Django 5.2.5 on 2026-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_reviewreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyback',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено'),
        ),
        migrations.AddField(
            model_name='buyback',
            name='step_started_at',
            field=models.DateTimeField(blank=True, help_text='Когда пользователь начал текущий шаг', null=True, verbose_name='Начало текущего шага'),
        ),
    ]
