# Generated by Django 6.0.1 on 2026-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_add_step_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyback',
            name='custom_publish_at',
            field=models.DateTimeField(blank=True, help_text='Если задано — используется вместо стандартного времени из шага', null=True, verbose_name='Назначенное время публикации'),
        ),
    ]
