# Generated by Django 5.2.5 on 2026-02-05 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_product_limit_per_user_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('title', models.CharField(blank=True, help_text='Короткий заголовок шага', max_length=255, verbose_name='Заголовок')),
                ('step_type', models.CharField(choices=[('photo', 'Загрузка фото'), ('article_check', 'Проверка артикула'), ('text_moderated', 'Текст с модерацией'), ('confirm', 'Подтверждение'), ('order_number', 'Номер заказа'), ('choice', 'Выбор варианта'), ('check_link', 'Ссылка на чек'), ('payment_details', 'Реквизиты для выплаты')], max_length=20, verbose_name='Тип шага')),
                ('instruction', models.TextField(help_text='Текст который увидит пользователь', verbose_name='Инструкция')),
                ('image', models.ImageField(blank=True, help_text='Картинка-инструкция для шага', upload_to='task_steps/', verbose_name='Изображение')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='correct_article, choices, hint и т.д.', verbose_name='Настройки')),
                ('timeout_minutes', models.PositiveIntegerField(blank=True, help_text='Время на выполнение. Пусто = без ограничения', null=True, verbose_name='Таймаут (минут)')),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Напоминание через (минут)')),
                ('reminder_text', models.TextField(blank=True, help_text='Переменные: {remaining_time}, {task_title}, {step_title}', verbose_name='Текст напоминания')),
                ('requires_moderation', models.BooleanField(default=False, help_text='Если да — ответ идёт на проверку менеджеру', verbose_name='Требует модерации')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='catalog.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Шаг задания',
                'verbose_name_plural': 'Шаги заданий',
                'ordering': ['task', 'order'],
                'unique_together': {('task', 'order')},
            },
        ),
    ]
