# Generated by Django 5.2.5 on 2026-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='publish_time',
            field=models.TimeField(blank=True, help_text='Только для типа "Публикация отзыва"', null=True, verbose_name='Время публикации (МСК)'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='step_type',
            field=models.CharField(choices=[('photo', 'Загрузка фото'), ('article_check', 'Проверка артикула'), ('text_moderated', 'Текст с модерацией'), ('confirm', 'Подтверждение'), ('order_number', 'Номер заказа'), ('choice', 'Выбор варианта'), ('check_link', 'Ссылка на чек'), ('payment_details', 'Реквизиты для выплаты'), ('publish_review', 'Публикация отзыва')], max_length=20, verbose_name='Тип шага'),
        ),
    ]
