# Generated by Django 6.0.1 on 2026-02-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_taskstep_publish_time_alter_taskstep_step_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название шаблона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон шагов',
                'verbose_name_plural': 'Шаблоны шагов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('step_type', models.CharField(choices=[('photo', 'Загрузка фото'), ('article_check', 'Проверка артикула'), ('text_moderated', 'Текст с модерацией'), ('confirm', 'Подтверждение'), ('order_number', 'Номер заказа'), ('choice', 'Выбор варианта'), ('check_link', 'Ссылка на чек'), ('payment_details', 'Реквизиты для выплаты'), ('publish_review', 'Публикация отзыва')], max_length=20, verbose_name='Тип шага')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('image', models.ImageField(blank=True, upload_to='step_templates/', verbose_name='Изображение')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('publish_time', models.TimeField(blank=True, null=True, verbose_name='Время публикации (МСК)')),
                ('timeout_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Таймаут (минут)')),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Напоминание через (минут)')),
                ('reminder_text', models.TextField(blank=True, verbose_name='Текст напоминания')),
                ('requires_moderation', models.BooleanField(default=False, verbose_name='Требует модерации')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='steps.steptemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Шаг шаблона',
                'verbose_name_plural': 'Шаги шаблона',
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
    ]
