# Generated by Django 5.2.5 on 2026-01-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Выкуп футболки с отзывом', max_length=255, verbose_name='Название задания')),
                ('reward', models.DecimalField(decimal_places=2, help_text='Сумма сверх компенсации за товар', max_digits=10, verbose_name='Вознаграждение')),
                ('cashback', models.DecimalField(decimal_places=2, help_text='Возврат стоимости товара', max_digits=10, verbose_name='Компенсация за товар')),
                ('quantity_total', models.PositiveIntegerField(default=1, verbose_name='Всего выкупов')),
                ('quantity_completed', models.PositiveIntegerField(default=0, verbose_name='Выполнено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Buyback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='Текущий шаг')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('on_review', 'На проверке'), ('completed', 'Завершён'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('expired', 'Истёк')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки админа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buybacks', to='account.telegramuser', verbose_name='Пользователь')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buybacks', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Выкуп',
                'verbose_name_plural': 'Выкупы',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('step_type', models.CharField(choices=[('photo', 'Загрузка фото'), ('article_check', 'Проверка артикула'), ('text_moderated', 'Текст с модерацией'), ('confirm', 'Подтверждение'), ('order_number', 'Номер заказа'), ('choice', 'Выбор варианта')], max_length=20, verbose_name='Тип шага')),
                ('instruction', models.TextField(help_text='Текст, который увидит пользователь', verbose_name='Инструкция')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='correct_article, choices, hint и т.д.', verbose_name='Настройки')),
                ('timeout_hours', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым если без ограничения', null=True, verbose_name='Таймаут (часы)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Шаг задания',
                'verbose_name_plural': 'Шаги заданий',
                'ordering': ['task', 'order'],
                'unique_together': {('task', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BuybackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(default=dict, help_text='photo, text, value и т.д.', verbose_name='Данные ответа')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('auto_approved', 'Авто-одобрен')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('admin_edited_text', models.TextField(blank=True, help_text='Для text_moderated — текст после правок админа', verbose_name='Исправленный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('buyback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tasks.buyback', verbose_name='Выкуп')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='tasks.taskstep', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Ответ на шаг',
                'verbose_name_plural': 'Ответы на шаги',
                'ordering': ['buyback', 'step__order'],
            },
        ),
    ]
