# Generated by Django 5.2.5 on 2026-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quantity_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quantity_total',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
        migrations.AddField(
            model_name='task',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма которую получит выкупщик', max_digits=10, verbose_name='Выплата'),
            preserve_default=False,
        ),
    ]
