# Generated by Django 5.2.5 on 2026-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_cashback_remove_task_quantity_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='requires_moderation',
            field=models.BooleanField(default=False, help_text='Если включено — ответ отправляется на проверку модератору', verbose_name='Требует модерации'),
        ),
    ]
