# Generated by Django 5.2.5 on 2026-01-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskstep_requires_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='image',
            field=models.ImageField(blank=True, help_text='Опциональная картинка-инструкция для шага', upload_to='task_steps/', verbose_name='Изображение'),
        ),
    ]
