# Generated by Django 5.2.5 on 2026-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskstep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='booking_timeout_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Сколько минут бронируется товар после взятия задания', verbose_name='Время бронирования (минут)'),
        ),
    ]
