# Generated by Django 5.2.5 on 2026-01-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_booking_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='title',
            field=models.CharField(blank=True, help_text='Короткий заголовок шага (опционально)', max_length=255, verbose_name='Заголовок'),
        ),
    ]
