# Generated by Django 5.2.5 on 2026-02-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskstep_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='booking_timeout_minutes',
        ),
        migrations.RemoveField(
            model_name='taskstep',
            name='timeout_hours',
        ),
        migrations.AddField(
            model_name='taskstep',
            name='reminder_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Через сколько минут отправить напоминание', null=True, verbose_name='Напоминание через (минут)'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='reminder_text',
            field=models.TextField(blank=True, help_text='Текст который получит пользователь. Доступные переменные: {remaining_time}, {task_title}, {step_title}', verbose_name='Текст напоминания'),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='timeout_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым если без ограничения', null=True, verbose_name='Время на выполнение (минут)'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='instruction',
            field=models.TextField(help_text='Подробный текст, который увидит пользователь', verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='requires_moderation',
            field=models.BooleanField(default=False, help_text='Если включено — время не ограничено, бронь не отменяется', verbose_name='Требует модерации'),
        ),
    ]
