# Generated by Django 5.2.5 on 2026-02-05 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('payment_bank', models.CharField(max_length=100, verbose_name='Банк')),
                ('payment_name', models.CharField(max_length=255, verbose_name='ФИО получателя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Выплачено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('buyback', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='pipeline.buyback', verbose_name='Выкуп')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='account.telegramuser', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
