# Generated by Django 5.2.5 on 2026-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('wb_article', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Артикул WB')),
                ('price', models.DecimalField(decimal_places=2, help_text='Текущая цена товара на Wildberries', max_digits=10, verbose_name='Цена на WB')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Фото товара')),
                ('description', models.TextField(blank=True, help_text='Краткое описание для выкупщиков', verbose_name='Описание')),
                ('quantity_total', models.PositiveIntegerField(default=0, help_text='Общее количество товаров доступных для выкупа', verbose_name='Всего на выкуп')),
                ('quantity_completed', models.PositiveIntegerField(default=0, verbose_name='Выкуплено')),
                ('limit_per_user', models.PositiveIntegerField(default=1, help_text='Сколько раз один человек может выкупить (0 = без лимита)', verbose_name='Лимит на пользователя')),
                ('limit_per_user_days', models.PositiveIntegerField(default=0, help_text='За какой период считать (0 = за всё время, 1 = в сутки)', verbose_name='Период лимита (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
