# Generated by Django 5.2.5 on 2026-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('wb_article', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Артикул WB')),
                ('price', models.DecimalField(decimal_places=2, help_text='Текущая цена товара на Wildberries', max_digits=10, verbose_name='Цена на WB')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Фото товара')),
                ('description', models.TextField(blank=True, help_text='Краткое описание для выкупщиков', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
