# Generated by Django 5.2.5 on 2026-02-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limit_per_user_days',
            field=models.PositiveIntegerField(default=0, help_text='За какой период считать (0 = за всё время)', verbose_name='Период лимита (дней)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_total',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество товаров для выкупа', verbose_name='Всего на выкуп'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Выкуп футболки с отзывом', max_length=255, verbose_name='Название задания')),
                ('payout', models.DecimalField(decimal_places=2, help_text='Сумма которую получит выкупщик', max_digits=10, verbose_name='Выплата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
