# Generated by Django 5.2.5 on 2026-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limit_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Сколько раз один человек может выкупить (0 = без лимита)', verbose_name='Лимит на пользователя'),
        ),
        migrations.AddField(
            model_name='product',
            name='limit_per_user_days',
            field=models.PositiveIntegerField(default=0, help_text='За какой период считать (0 = за всё время, 1 = в сутки)', verbose_name='Период лимита (дней)'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Выкуплено'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_total',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество товаров доступных для выкупа', verbose_name='Всего на выкуп'),
        ),
    ]
